# Site settings
locale: "en-US"
baseurl: "/bookworm"
url: "http://alertbox.github.io"

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
  
  # _chapters
  - scope: 
      path: "_chapters"
      type: chapters
    values:
      layout: chapter

# Optional features
animated: false
extended_fonts: false
enable_anchorjs: false

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Disqus book comments
# (leave blank to disable Disqus)
disqus_shortname:

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Gems
plugins:
  - github-pages
  - jemoji
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap   
  - jekyll-gist
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
    
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - README.md
  - screenshot.png
  - robots.txt
  - vendor
  - '*.gemspec'
  - '*.gem'
  - '*.sh'
include:
  - _pages
