# Site settings
locale: "en-US"
title: Bookworm
description: "Jekyll theme for books and creative writing that emphasizes content rather than aesthetic fluff."
baseurl: "/bookworm"
url: "http://alertbox.github.io"
bugs: "https://github.com/alertbox/bookworm/issues/new?assignees=&labels=&template=bug_report.md&title="
repository: "/bookworm"
date_format: "%b %-d, %Y"

# Site author
author: 
  name: "Kosala Nuwan Perera"
  avatar: "https://avatars1.githubusercontent.com/u/958227?s=460&u=9b166f138e17fd8a8a60177dbbaa79deff890ac6&v=4"
  email: kosala.nuwan@gmail.com
  # Social
  github_username: kosalanuwan
  twitter_handler: kosalanuwan
  linkedin_username: kosalanuwan
  medium_id: kosalanuwan

# Collections
collections:
  chapters:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  
  # _chapters
  - scope: 
      path: ""
      type: chapters
    values:
      layout: chapter

# Optional features
animated: false
extended_fonts: false
enable_anchorjs: false

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Disqus book comments
# (leave blank to disable Disqus)
disqus_shortname:

text:
  pagination:
    next: "Next"
    previous: "Previous"
  index:
    title: "Chapters"
    coming_soon: "A work in-progress..."

# Build settings
markdown:     kramdown
permalink:    pretty
sass:
  style: compressed

# Use Bookworm gem-based theme
# - uncomment will use the remote theme instead
# remote_theme: alertbox/bookworm

plugins:
  - jekyll-feed
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - README.md
  - screenshot.png
  - robots.txt
  - vendor
  - bookworm.gemspec
  - '*.gem'
  - '*.sh'
include:
  - _pages
