name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-gh-pages@v3
        with:
          enable_jekyll: true
          personal_token: ${{ secrets.JEKYLL_PAT }}
          publish_dir: ./_site
        # env:
        #   JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}