name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
  
    steps:
      - name: Build
        uses: ./github/workflows/build@master

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@master
        with:
          # keep_files: true
          enable_jekyll: true
          personal_token: ${{ secrets.JEKYLL_PAT }}
          publish_dir: ./_site