name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@master
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.0.2
        env:
          # Ideally use GITHUB_TOKEN but it gives error for this action.
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}

      # - name: Deploy to gh-pages
      #   uses: peaceiris/actions-gh-pages@main
      #   with:
      #     # keep_files: true
      #     enable_jekyll: true
      #     personal_token: ${{ secrets.JEKYLL_PAT }}
      #     publish_dir: ./_site